/**
 * Attitude Free Fire Nicknames — Database & Persona Taxonomy
 * Curated base gaming identities categorized by persona, concept, tone, and relationships.
 */

const ATTITUDE_PERSONAS = [
  {
    id: "boss",
    name: "Boss",
    icon: "👑",
    badge: "Authority",
    tagline: "Leader energy & dominion",
    description: "Authoritative, commanding identities designed for shot-callers, guild masters, and dominant players.",
    sampleNames: ["Reign", "Titan", "Chief", "Prime"],
    complementaryIds: ["cold", "royal", "confident"],
    oppositeIds: ["rebel", "silent"]
  },
  {
    id: "fearless",
    name: "Fearless",
    icon: "🔥",
    badge: "Courage",
    tagline: "Bold & front-line aggressive",
    description: "High-octane warrior handles that project zero hesitation, relentless pushes, and unflinching confidence.",
    sampleNames: ["Blaze", "Valor", "Bravo", "Vanguard"],
    complementaryIds: ["bold", "savage", "unstoppable"],
    oppositeIds: ["cold", "silent"]
  },
  {
    id: "rebel",
    name: "Rebel",
    icon: "😈",
    badge: "Outlaw",
    tagline: "Unconventional nonconformist",
    description: "Defiant, anti-meta personas that break conventions and play strictly by their own rules.",
    sampleNames: ["Rogue", "Vex", "Nomad", "Outlaw"],
    complementaryIds: ["lone-wolf", "savage", "mysterious"],
    oppositeIds: ["royal", "boss"]
  },
  {
    id: "lone-wolf",
    name: "Lone Wolf",
    icon: "🐺",
    badge: "Solo",
    tagline: "Independent & detached",
    description: "Self-reliant solo operative identities. Perfect for solo rank pushers who thrive without a squad.",
    sampleNames: ["Rogue", "Solo", "Nomad", "Drifter"],
    complementaryIds: ["mysterious", "rebel", "cold"],
    oppositeIds: ["boss", "royal"]
  },
  {
    id: "cold",
    name: "Cold",
    icon: "🧊",
    badge: "Calculated",
    tagline: "Calm, icy & unbothered",
    description: "Emotionless precision, clinical decision-making, and unflappable clutch composure under pressure.",
    sampleNames: ["Frost", "Zero", "Vanta", "Glacier"],
    complementaryIds: ["boss", "silent", "mysterious"],
    oppositeIds: ["fearless", "savage"]
  },
  {
    id: "bold",
    name: "Bold",
    icon: "⚡",
    badge: "Impact",
    tagline: "High-confidence impact",
    description: "Punchy, electric handles that demand attention the moment your name appears in the elimination feed.",
    sampleNames: ["Apex", "Storm", "Havoc", "Striker"],
    complementaryIds: ["fearless", "unstoppable", "confident"],
    oppositeIds: ["silent", "mysterious"]
  },
  {
    id: "mysterious",
    name: "Mysterious",
    icon: "🌑",
    badge: "Enigma",
    tagline: "Dark, veiled & unseen",
    description: "Cryptic, occult, and shadow-veiled handles that leave opponents guessing your true origin.",
    sampleNames: ["Phantom", "Ghost", "Cipher", "Onyx"],
    complementaryIds: ["lone-wolf", "cold", "silent"],
    oppositeIds: ["bold", "fearless"]
  },
  {
    id: "royal",
    name: "Royal",
    icon: "♛",
    badge: "Prestige",
    tagline: "Monarch & sovereign status",
    description: "Aristocratic, regal titles of supreme rank, imperial poise, and elite gaming prestige.",
    sampleNames: ["Kaiser", "Monarch", "Crown", "Rex"],
    complementaryIds: ["boss", "confident", "cold"],
    oppositeIds: ["rebel", "savage"]
  },
  {
    id: "silent",
    name: "Silent",
    icon: "🥷",
    badge: "Stealth",
    tagline: "Quiet assassin & unseen shadow",
    description: "Zero noise, maximum lethality. Handles built for covert flankers and patient ambush snipers.",
    sampleNames: ["Shade", "Whisper", "Kage", "Specter"],
    complementaryIds: ["cold", "mysterious", "lone-wolf"],
    oppositeIds: ["bold", "fearless"]
  },
  {
    id: "savage",
    name: "Savage",
    icon: "💀",
    badge: "Ruthless",
    tagline: "Hard-edged competitive bite",
    description: "Vicious, predator-instinct handles that convey brutal squad wipes and no-mercy headshots.",
    sampleNames: ["Venom", "Viper", "Reaper", "Bane"],
    complementaryIds: ["fearless", "rebel", "unstoppable"],
    oppositeIds: ["royal", "cold"]
  },
  {
    id: "unstoppable",
    name: "Unstoppable",
    icon: "🚀",
    badge: "Momentum",
    tagline: "Relentless momentum & force",
    description: "Heavy juggernaut titles that signal an unstoppable steamroller pushing through enemy squads.",
    sampleNames: ["Colossus", "Rampage", "Overkill", "Titan"],
    complementaryIds: ["bold", "fearless", "boss"],
    oppositeIds: ["silent", "cold"]
  },
  {
    id: "confident",
    name: "Confident",
    icon: "😎",
    badge: "Swagger",
    tagline: "Clean assurance & swagger",
    description: "Sleek, effortless mastery. Handles that exude effortless skill without shouting.",
    sampleNames: ["Ace", "Karma", "Legend", "Zenith"],
    complementaryIds: ["boss", "royal", "bold"],
    oppositeIds: ["savage", "rebel"]
  }
];

const ATTITUDE_DATABASE = [
  // --- BOSS / LEADER IDENTITIES ---
  {
    id: "reign",
    baseName: "Reign",
    personas: ["boss", "royal"],
    concepts: ["rule", "throne", "authority", "dominion"],
    tone: ["commanding", "elite"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 REIGN 亗",
    extremeStyle: "꧁亗REIGN亗꧂",
    royalStyle: "♛REIGN♛",
    darkStyle: "☠REIGN☠",
    relatedIds: ["titan", "prime", "chief", "kaiser", "apex"]
  },
  {
    id: "titan",
    baseName: "Titan",
    personas: ["boss", "unstoppable", "bold"],
    concepts: ["giant", "strength", "power", "leader"],
    tone: ["heavy", "commanding"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 TITAN 亗",
    extremeStyle: "꧁亗TITAN亗꧂",
    royalStyle: "♛TITAN♛",
    darkStyle: "☠TITAN☠",
    relatedIds: ["reign", "colossus", "apex", "prime"]
  },
  {
    id: "chief",
    baseName: "Chief",
    personas: ["boss", "confident"],
    concepts: ["leader", "commander", "head", "authority"],
    tone: ["grounded", "commanding"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 CHIEF 亗",
    extremeStyle: "꧁CHIEF꧂",
    royalStyle: "♛CHIEF♛",
    darkStyle: "•|CHIEF|•",
    relatedIds: ["prime", "reign", "titan", "rex"]
  },
  {
    id: "prime",
    baseName: "Prime",
    personas: ["boss", "confident", "bold"],
    concepts: ["first", "optimum", "supreme", "apex"],
    tone: ["clean", "sharp"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 PRIME 亗",
    extremeStyle: "꧁PRIME꧂",
    royalStyle: "♛PRIME♛",
    darkStyle: "00·PRIME·00",
    relatedIds: ["apex", "chief", "reign", "zenith"]
  },
  {
    id: "apex",
    baseName: "Apex",
    personas: ["boss", "bold", "fearless"],
    concepts: ["peak", "predator", "top", "unbeaten"],
    tone: ["sharp", "commanding"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 APEX 亗",
    extremeStyle: "꧁亗APEX亗꧂",
    royalStyle: "♛APEX♛",
    darkStyle: "乂APEX乂",
    relatedIds: ["prime", "titan", "vortex", "zenith"]
  },
  {
    id: "kaiser",
    baseName: "Kaiser",
    personas: ["boss", "royal"],
    concepts: ["emperor", "monarch", "sovereign", "iron"],
    tone: ["elite", "commanding"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 KAISER 亗",
    extremeStyle: "꧁KAISER꧂",
    royalStyle: "♛KAISER♛",
    darkStyle: "☠KAISER☠",
    relatedIds: ["reign", "monarch", "rex", "crown"]
  },
  {
    id: "rex",
    baseName: "Rex",
    personas: ["boss", "royal", "confident"],
    concepts: ["king", "ruler", "crown"],
    tone: ["compact", "elite"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 REX 亗",
    extremeStyle: "『REX』",
    royalStyle: "♛REX♛",
    darkStyle: "•REX•",
    relatedIds: ["kaiser", "prime", "reign", "ace"]
  },
  {
    id: "warlord",
    baseName: "Warlord",
    personas: ["boss", "savage", "fearless"],
    concepts: ["conqueror", "war", "army", "general"],
    tone: ["brutal", "commanding"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 WARLORD 亗",
    extremeStyle: "꧁亗WARLORD亗꧂",
    royalStyle: "♛WARLORD♛",
    darkStyle: "☠WARLORD☠",
    relatedIds: ["reign", "havoc", "titan", "slayer"]
  },
  {
    id: "ironclad",
    baseName: "Ironclad",
    personas: ["boss", "unstoppable", "cold"],
    concepts: ["armor", "unbreakable", "shield", "steel"],
    tone: ["heavy", "fortified"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 IRONCLAD 亗",
    extremeStyle: "【IRONCLAD】",
    royalStyle: "♛IRONCLAD♛",
    darkStyle: "•|IRONCLAD|•",
    relatedIds: ["titan", "colossus", "overkill"]
  },

  // --- REBEL / OUTLAW IDENTITIES ---
  {
    id: "rogue",
    baseName: "Rogue",
    personas: ["rebel", "lone-wolf", "mysterious"],
    concepts: ["outlaw", "independent", "unconventional", "renegade"],
    tone: ["bold", "covert"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 ROGUE 亗",
    extremeStyle: "꧁ROGUE꧂",
    royalStyle: "♛ROGUE♛",
    darkStyle: "乂ROGUE乂",
    relatedIds: ["nomad", "drifter", "vex", "outlaw", "havoc"]
  },
  {
    id: "vex",
    baseName: "Vex",
    personas: ["rebel", "savage", "bold"],
    concepts: ["chaos", "annoyance", "sharp", "spite"],
    tone: ["electric", "edgy"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 VEX 亗",
    extremeStyle: "『VEX』",
    royalStyle: "♛VEX♛",
    darkStyle: "乂VEX乂",
    relatedIds: ["rogue", "havoc", "toxic", "riot"]
  },
  {
    id: "nomad",
    baseName: "Nomad",
    personas: ["rebel", "lone-wolf", "silent"],
    concepts: ["wanderer", "solitary", "desert", "survival"],
    tone: ["stealth", "independent"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 NOMAD 亗",
    extremeStyle: "꧁NOMAD꧂",
    royalStyle: "♛NOMAD♛",
    darkStyle: "•NOMAD•",
    relatedIds: ["drifter", "rogue", "solo", "phantom"]
  },
  {
    id: "drifter",
    baseName: "Drifter",
    personas: ["rebel", "lone-wolf"],
    concepts: ["traveler", "shadow", "unbound", "solo"],
    tone: ["detached", "cool"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 DRIFTER 亗",
    extremeStyle: "꧁DRIFTER꧂",
    royalStyle: "♛DRIFTER♛",
    darkStyle: "乂DRIFTER乂",
    relatedIds: ["nomad", "rogue", "solo", "ghost"]
  },
  {
    id: "outlaw",
    baseName: "Outlaw",
    personas: ["rebel", "savage", "fearless"],
    concepts: ["wanted", "bandit", "gunslinger", "bounty"],
    tone: ["aggressive", "bold"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 OUTLAW 亗",
    extremeStyle: "꧁亗OUTLAW亗꧂",
    royalStyle: "♛OUTLAW♛",
    darkStyle: "☠OUTLAW☠",
    relatedIds: ["rogue", "vandal", "rebel-x", "havoc"]
  },
  {
    id: "renegade",
    baseName: "Renegade",
    personas: ["rebel", "lone-wolf", "fearless"],
    concepts: ["traitor", "mutiny", "unruled", "defiant"],
    tone: ["fierce", "bold"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 RENEGADE 亗",
    extremeStyle: "꧁RENEGADE꧂",
    royalStyle: "♛RENEGADE♛",
    darkStyle: "☠RENEGADE☠",
    relatedIds: ["rogue", "outlaw", "vandal", "bane"]
  },
  {
    id: "vandal",
    baseName: "Vandal",
    personas: ["rebel", "savage", "bold"],
    concepts: ["destroyer", "chaos", "graffiti", "riot"],
    tone: ["destructive", "bold"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 VANDAL 亗",
    extremeStyle: "【VANDAL】",
    royalStyle: "♛VANDAL♛",
    darkStyle: "乂VANDAL乂",
    relatedIds: ["outlaw", "havoc", "riot", "vex"]
  },
  {
    id: "riot",
    baseName: "Riot",
    personas: ["rebel", "fearless", "bold"],
    concepts: ["anarchy", "chaos", "rebellion", "uprising"],
    tone: ["explosive", "wild"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 RIOT 亗",
    extremeStyle: "『RIOT』",
    royalStyle: "♛RIOT♛",
    darkStyle: "⚡RIOT⚡",
    relatedIds: ["havoc", "vandal", "vex", "outlaw"]
  },

  // --- LONE WOLF / INDEPENDENT IDENTITIES ---
  {
    id: "solo",
    baseName: "Solo",
    personas: ["lone-wolf", "confident"],
    concepts: ["single", "unassisted", "one-man", "independent"],
    tone: ["minimal", "confident"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 SOLO 亗",
    extremeStyle: "『SOLO』",
    royalStyle: "♛SOLO♛",
    darkStyle: "•SOLO•",
    relatedIds: ["nomad", "drifter", "rogue", "ace"]
  },
  {
    id: "wolf",
    baseName: "Wolf",
    personas: ["lone-wolf", "savage", "fearless"],
    concepts: ["predator", "pack", "howl", "fangs"],
    tone: ["wild", "focused"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 WOLF 亗",
    extremeStyle: "꧁WOLF꧂",
    royalStyle: "♛WOLF♛",
    darkStyle: "☠WOLF☠",
    relatedIds: ["fenrir", "hunter", "nomad", "solo"]
  },
  {
    id: "fenrir",
    baseName: "Fenrir",
    personas: ["lone-wolf", "savage", "unstoppable"],
    concepts: ["mythic", "norse", "beast", "unbound"],
    tone: ["legendary", "ferocious"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 FENRIR 亗",
    extremeStyle: "꧁亗FENRIR亗꧂",
    royalStyle: "♛FENRIR♛",
    darkStyle: "☠FENRIR☠",
    relatedIds: ["wolf", "draco", "hydra", "beast"]
  },
  {
    id: "exile",
    baseName: "Exile",
    personas: ["lone-wolf", "mysterious", "rebel"],
    concepts: ["banished", "outsider", "wanderer", "silent"],
    tone: ["dark", "detached"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 EXILE 亗",
    extremeStyle: "『EXILE』",
    royalStyle: "♛EXILE♛",
    darkStyle: "•|EXILE|•",
    relatedIds: ["nomad", "rogue", "void", "ghost"]
  },
  {
    id: "stranger",
    baseName: "Stranger",
    personas: ["lone-wolf", "mysterious"],
    concepts: ["unknown", "drifter", "unnamed", "shadow"],
    tone: ["enigmatic", "quiet"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 STRANGER 亗",
    extremeStyle: "꧁STRANGER꧂",
    royalStyle: "♛STRANGER♛",
    darkStyle: "•STRANGER•",
    relatedIds: ["nomad", "cipher", "phantom", "ghost"]
  },

  // --- COLD / CALCULATED IDENTITIES ---
  {
    id: "frost",
    baseName: "Frost",
    personas: ["cold", "silent", "confident"],
    concepts: ["ice", "subzero", "freeze", "crystal", "chill"],
    tone: ["clean", "sharp", "calm"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 FROST 亗",
    extremeStyle: "꧁FROST꧂",
    royalStyle: "♛FROST♛",
    darkStyle: "•FROST•",
    relatedIds: ["zero", "vanta", "glacier", "blizzard", "chill"]
  },
  {
    id: "zero",
    baseName: "Zero",
    personas: ["cold", "silent", "mysterious"],
    concepts: ["absolute-zero", "null", "nothing", "void"],
    tone: ["minimal", "clinical"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 ZERO 亗",
    extremeStyle: "『ZERO』",
    royalStyle: "♛ZERO♛",
    darkStyle: "00·ZERO·00",
    relatedIds: ["frost", "vanta", "cipher", "void"]
  },
  {
    id: "vanta",
    baseName: "Vanta",
    personas: ["cold", "mysterious", "silent"],
    concepts: ["darkest-black", "absorption", "stealth", "void"],
    tone: ["abyssal", "clinical"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 VANTA 亗",
    extremeStyle: "【VANTA】",
    royalStyle: "♛VANTA♛",
    darkStyle: "•|VANTA|•",
    relatedIds: ["zero", "onyx", "void", "frost"]
  },
  {
    id: "glacier",
    baseName: "Glacier",
    personas: ["cold", "unstoppable", "boss"],
    concepts: ["ice-sheet", "crush", "slow", "unstoppable"],
    tone: ["heavy", "stoic"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 GLACIER 亗",
    extremeStyle: "꧁GLACIER꧂",
    royalStyle: "♛GLACIER♛",
    darkStyle: "•GLACIER•",
    relatedIds: ["frost", "titan", "colossus", "blizzard"]
  },
  {
    id: "subzero",
    baseName: "SubZero",
    personas: ["cold", "savage", "fearless"],
    concepts: ["freezing", "ninja", "ice-strike", "combat"],
    tone: ["lethal", "cold"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 SUBZERO 亗",
    extremeStyle: "꧁亗SUBZERO亗꧂",
    royalStyle: "♛SUBZERO♛",
    darkStyle: "☠SUBZERO☠",
    relatedIds: ["frost", "zero", "glacier", "ronin"]
  },
  {
    id: "blizzard",
    baseName: "Blizzard",
    personas: ["cold", "bold", "fearless"],
    concepts: ["storm", "whiteout", "gale", "freeze"],
    tone: ["stormy", "wild"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 BLIZZARD 亗",
    extremeStyle: "꧁BLIZZARD꧂",
    royalStyle: "♛BLIZZARD♛",
    darkStyle: "彡BLIZZARD彡",
    relatedIds: ["frost", "storm", "glacier", "havoc"]
  },

  // --- FEARLESS / BOLD / POWER IDENTITIES ---
  {
    id: "blaze",
    baseName: "Blaze",
    personas: ["fearless", "bold"],
    concepts: ["fire", "inferno", "heat", "burst"],
    tone: ["energetic", "aggressive"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 BLAZE 亗",
    extremeStyle: "꧁BLAZE꧂",
    royalStyle: "♛BLAZE♛",
    darkStyle: "🔥BLAZE🔥",
    relatedIds: ["inferno", "storm", "havoc", "fury"]
  },
  {
    id: "valor",
    baseName: "Valor",
    personas: ["fearless", "confident", "royal"],
    concepts: ["courage", "hero", "bravery", "honor"],
    tone: ["noble", "bold"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 VALOR 亗",
    extremeStyle: "꧁VALOR꧂",
    royalStyle: "♛VALOR♛",
    darkStyle: "★VALOR★",
    relatedIds: ["bravo", "knight", "prime", "legend"]
  },
  {
    id: "havoc",
    baseName: "Havoc",
    personas: ["fearless", "bold", "rebel"],
    concepts: ["chaos", "destruction", "wrecker", "wild"],
    tone: ["explosive", "ruthless"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 HAVOC 亗",
    extremeStyle: "꧁亗HAVOC亗꧂",
    royalStyle: "♛HAVOC♛",
    darkStyle: "☠HAVOC☠",
    relatedIds: ["chaos", "riot", "vandal", "bane"]
  },
  {
    id: "storm",
    baseName: "Storm",
    personas: ["bold", "fearless", "unstoppable"],
    concepts: ["thunder", "tempest", "lightning", "force"],
    tone: ["raging", "powerful"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 STORM 亗",
    extremeStyle: "꧁STORM꧂",
    royalStyle: "♛STORM♛",
    darkStyle: "⚡STORM⚡",
    relatedIds: ["blaze", "vortex", "surge", "havoc"]
  },
  {
    id: "vortex",
    baseName: "Vortex",
    personas: ["bold", "mysterious", "unstoppable"],
    concepts: ["spiral", "cyclone", "gravity", "energy"],
    tone: ["kinetic", "cyber"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 VORTEX 亗",
    extremeStyle: "꧁亗VORTEX亗꧂",
    royalStyle: "♛VORTEX♛",
    darkStyle: "乂VORTEX乂",
    relatedIds: ["storm", "pulse", "matrix", "zenith"]
  },
  {
    id: "inferno",
    baseName: "Inferno",
    personas: ["fearless", "savage", "bold"],
    concepts: ["hellfire", "burn", "cataclysm", "blaze"],
    tone: ["scorching", "aggressive"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 INFERNO 亗",
    extremeStyle: "꧁亗INFERNO亗꧂",
    royalStyle: "♛INFERNO♛",
    darkStyle: "🔥INFERNO🔥",
    relatedIds: ["blaze", "havoc", "fury", "draco"]
  },
  {
    id: "striker",
    baseName: "Striker",
    personas: ["bold", "confident", "fearless"],
    concepts: ["attacker", "marksman", "punch", "assault"],
    tone: ["direct", "athletic"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 STRIKER 亗",
    extremeStyle: "꧁STRIKER꧂",
    royalStyle: "♛STRIKER♛",
    darkStyle: "乂STRIKER乂",
    relatedIds: ["hunter", "slayer", "bullet", "apex"]
  },
  {
    id: "vanguard",
    baseName: "Vanguard",
    personas: ["fearless", "boss", "confident"],
    concepts: ["frontline", "spearhead", "first", "defense"],
    tone: ["resolute", "commanding"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 VANGUARD 亗",
    extremeStyle: "【VANGUARD】",
    royalStyle: "♛VANGUARD♛",
    darkStyle: "•|VANGUARD|•",
    relatedIds: ["valor", "prime", "titan", "chief"]
  },

  // --- MYSTERIOUS / SILENT IDENTITIES ---
  {
    id: "phantom",
    baseName: "Phantom",
    personas: ["mysterious", "silent", "lone-wolf"],
    concepts: ["ghost", "specter", "unseen", "stealth"],
    tone: ["haunting", "covert"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 PHANTOM 亗",
    extremeStyle: "꧁PHANTOM꧂",
    royalStyle: "♛PHANTOM♛",
    darkStyle: "☠PHANTOM☠",
    relatedIds: ["ghost", "specter", "shadow", "onyx"]
  },
  {
    id: "ghost",
    baseName: "Ghost",
    personas: ["mysterious", "silent", "lone-wolf"],
    concepts: ["wraith", "vanish", "invisible", "spirit"],
    tone: ["ethereal", "minimal"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 GHOST 亗",
    extremeStyle: "『GHOST』",
    royalStyle: "♛GHOST♛",
    darkStyle: "•GHOST•",
    relatedIds: ["phantom", "specter", "shade", "cipher"]
  },
  {
    id: "shadow",
    baseName: "Shadow",
    personas: ["mysterious", "silent", "cold"],
    concepts: ["darkness", "stealth", "stalker", "eclipse"],
    tone: ["classic", "covert"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 SHADOW 亗",
    extremeStyle: "꧁亗SHADOW亗꧂",
    royalStyle: "♛SHADOW♛",
    darkStyle: "乂SHADOW乂",
    relatedIds: ["phantom", "ghost", "onyx", "kage"]
  },
  {
    id: "cipher",
    baseName: "Cipher",
    personas: ["mysterious", "cold", "silent"],
    concepts: ["code", "cryptic", "secret", "algorithm"],
    tone: ["cyber", "enigmatic"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 CIPHER 亗",
    extremeStyle: "⟦CIPHER⟧",
    royalStyle: "♛CIPHER♛",
    darkStyle: "//CIPHER//",
    relatedIds: ["matrix", "zero", "enigma", "ghost"]
  },
  {
    id: "onyx",
    baseName: "Onyx",
    personas: ["mysterious", "cold", "royal"],
    concepts: ["gemstone", "black", "precious", "shield"],
    tone: ["sleek", "rare"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 ONYX 亗",
    extremeStyle: "【ONYX】",
    royalStyle: "♛ONYX♛",
    darkStyle: "•|ONYX|•",
    relatedIds: ["vanta", "shadow", "void", "obsidian"]
  },
  {
    id: "void",
    baseName: "Void",
    personas: ["mysterious", "cold", "savage"],
    concepts: ["abyss", "empty", "black-hole", "cosmic"],
    tone: ["deep", "ominous"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 VOID 亗",
    extremeStyle: "꧁VOID꧂",
    royalStyle: "♛VOID♛",
    darkStyle: "☠VOID☠",
    relatedIds: ["abyss", "vanta", "zero", "phantom"]
  },
  {
    id: "kage",
    baseName: "Kage",
    personas: ["silent", "lone-wolf", "savage"],
    concepts: ["shadow-ninja", "japanese", "stealth", "blade"],
    tone: ["lethal", "covert"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 KAGE 亗",
    extremeStyle: "『KAGE』",
    royalStyle: "♛KAGE♛",
    darkStyle: "乂KAGE乂",
    relatedIds: ["ronin", "shadow", "specter", "ninja"]
  },
  {
    id: "whisper",
    baseName: "Whisper",
    personas: ["silent", "mysterious"],
    concepts: ["soft", "deadly", "wind", "silent-kill"],
    tone: ["delicate", "lethal"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 WHISPER 亗",
    extremeStyle: "꧁WHISPER꧂",
    royalStyle: "♛WHISPER♛",
    darkStyle: "•WHISPER•",
    relatedIds: ["shade", "ghost", "specter", "echo"]
  },
  {
    id: "specter",
    baseName: "Specter",
    personas: ["silent", "mysterious", "cold"],
    concepts: ["apparition", "stalker", "haunt", "stealth"],
    tone: ["menacing", "chilling"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 SPECTER 亗",
    extremeStyle: "꧁SPECTER꧂",
    royalStyle: "♛SPECTER♛",
    darkStyle: "☠SPECTER☠",
    relatedIds: ["phantom", "ghost", "shadow", "kage"]
  },

  // --- SAVAGE / RUTHLESS IDENTITIES ---
  {
    id: "venom",
    baseName: "Venom",
    personas: ["savage", "fearless", "rebel"],
    concepts: ["poison", "fatal", "bite", "toxic"],
    tone: ["lethal", "aggressive"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 VENOM 亗",
    extremeStyle: "꧁亗VENOM亗꧂",
    royalStyle: "♛VENOM♛",
    darkStyle: "☣VENOM☣",
    relatedIds: ["viper", "bane", "cobra", "toxic"]
  },
  {
    id: "viper",
    baseName: "Viper",
    personas: ["savage", "silent", "fearless"],
    concepts: ["snake", "strike", "speed", "lethal"],
    tone: ["fast", "venomous"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 VIPER 亗",
    extremeStyle: "꧁VIPER꧂",
    royalStyle: "♛VIPER♛",
    darkStyle: "乂VIPER乂",
    relatedIds: ["venom", "cobra", "fang", "striker"]
  },
  {
    id: "reaper",
    baseName: "Reaper",
    personas: ["savage", "mysterious", "boss"],
    concepts: ["death", "scythe", "harvest", "grim"],
    tone: ["ominous", "deadly"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 REAPER 亗",
    extremeStyle: "꧁亗REAPER亗꧂",
    royalStyle: "♛REAPER♛",
    darkStyle: "☠REAPER☠",
    relatedIds: ["bane", "slayer", "venom", "nemesis"]
  },
  {
    id: "bane",
    baseName: "Bane",
    personas: ["savage", "unstoppable", "boss"],
    concepts: ["ruin", "curse", "brute", "scourge"],
    tone: ["heavy", "ruthless"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 BANE 亗",
    extremeStyle: "【BANE】",
    royalStyle: "♛BANE♛",
    darkStyle: "☠BANE☠",
    relatedIds: ["reaper", "havoc", "venom", "warlord"]
  },
  {
    id: "slayer",
    baseName: "Slayer",
    personas: ["savage", "fearless", "bold"],
    concepts: ["executioner", "hunter", "blade", "blood"],
    tone: ["sharp", "aggressive"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 SLAYER 亗",
    extremeStyle: "꧁SLAYER꧂",
    royalStyle: "♛SLAYER♛",
    darkStyle: "⚔SLAYER⚔",
    relatedIds: ["hunter", "reaper", "striker", "warlord"]
  },
  {
    id: "nemesis",
    baseName: "Nemesis",
    personas: ["savage", "mysterious", "unstoppable"],
    concepts: ["rival", "downfall", "retribution", "fate"],
    tone: ["heavy", "relentless"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 NEMESIS 亗",
    extremeStyle: "꧁NEMESIS꧂",
    royalStyle: "♛NEMESIS♛",
    darkStyle: "☠NEMESIS☠",
    relatedIds: ["reaper", "bane", "karma", "overkill"]
  },

  // --- UNSTOPPABLE / MOMENTUM IDENTITIES ---
  {
    id: "colossus",
    baseName: "Colossus",
    personas: ["unstoppable", "boss"],
    concepts: ["giant", "monument", "steel", "fortress"],
    tone: ["massive", "unshakable"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 COLOSSUS 亗",
    extremeStyle: "【COLOSSUS】",
    royalStyle: "♛COLOSSUS♛",
    darkStyle: "•|COLOSSUS|•",
    relatedIds: ["titan", "glacier", "overkill", "juggernaut"]
  },
  {
    id: "overkill",
    baseName: "Overkill",
    personas: ["unstoppable", "fearless", "savage"],
    concepts: ["excess", "extreme", "firepower", "wipe"],
    tone: ["explosive", "ruthless"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 OVERKILL 亗",
    extremeStyle: "꧁亗OVERKILL亗꧂",
    royalStyle: "♛OVERKILL♛",
    darkStyle: "☠OVERKILL☠",
    relatedIds: ["havoc", "rampage", "colossus", "bane"]
  },
  {
    id: "rampage",
    baseName: "Rampage",
    personas: ["unstoppable", "savage", "fearless"],
    concepts: ["spree", "berserk", "fury", "unstoppable"],
    tone: ["frenzied", "unstoppable"],
    lengthProfile: "medium",
    wordCount: 1,
    proStyle: "亗 RAMPAGE 亗",
    extremeStyle: "꧁RAMPAGE꧂",
    royalStyle: "♛RAMPAGE♛",
    darkStyle: "🔥RAMPAGE🔥",
    relatedIds: ["overkill", "havoc", "fury", "blaze"]
  },
  {
    id: "juggernaut",
    baseName: "Juggernaut",
    personas: ["unstoppable", "boss", "bold"],
    concepts: ["battering-ram", "momentum", "unstoppable-force"],
    tone: ["heavy", "indomitable"],
    lengthProfile: "long",
    wordCount: 1,
    proStyle: "亗 JUGGERNAUT 亗",
    extremeStyle: "【JUGGERNAUT】",
    royalStyle: "♛JUGGERNAUT♛",
    darkStyle: "•|JUGGERNAUT|•",
    relatedIds: ["colossus", "titan", "overkill", "ironclad"]
  },

  // --- CONFIDENT / SWAGGER IDENTITIES ---
  {
    id: "ace",
    baseName: "Ace",
    personas: ["confident", "bold", "boss"],
    concepts: ["first", "best", "winner", "trump-card"],
    tone: ["clean", "sharp"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 ACE 亗",
    extremeStyle: "『ACE』",
    royalStyle: "♛ACE♛",
    darkStyle: "♠ACE♠",
    relatedIds: ["prime", "zenith", "solo", "rex"]
  },
  {
    id: "karma",
    baseName: "Karma",
    personas: ["confident", "mysterious", "cold"],
    concepts: ["retribution", "destiny", "fate", "balance"],
    tone: ["philosophical", "unshakable"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 KARMA 亗",
    extremeStyle: "꧁KARMA꧂",
    royalStyle: "♛KARMA♛",
    darkStyle: "☯KARMA☯",
    relatedIds: ["nemesis", "zenith", "cipher", "void"]
  },
  {
    id: "zenith",
    baseName: "Zenith",
    personas: ["confident", "royal", "boss"],
    concepts: ["highest-point", "celestial", "apex", "summit"],
    tone: ["elite", "luminous"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 ZENITH 亗",
    extremeStyle: "꧁ZENITH꧂",
    royalStyle: "♛ZENITH♛",
    darkStyle: "★ZENITH★",
    relatedIds: ["apex", "prime", "reign", "crown"]
  },
  {
    id: "legend",
    baseName: "Legend",
    personas: ["confident", "royal", "boss"],
    concepts: ["immortal", "famous", "hero", "master"],
    tone: ["prestige", "iconic"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 LEGEND 亗",
    extremeStyle: "꧁亗LEGEND亗꧂",
    royalStyle: "♛LEGEND♛",
    darkStyle: "★LEGEND★",
    relatedIds: ["valor", "prime", "reign", "myth"]
  },
  {
    id: "clutch",
    baseName: "Clutch",
    personas: ["confident", "cold", "bold"],
    concepts: ["esports", "1v4", "final-circle", "win"],
    tone: ["competitive", "reliable"],
    lengthProfile: "short",
    wordCount: 1,
    proStyle: "亗 CLUTCH 亗",
    extremeStyle: "『CLUTCH』",
    royalStyle: "♛CLUTCH♛",
    darkStyle: "⚡CLUTCH⚡",
    relatedIds: ["ace", "prime", "frost", "zero"]
  }
];

// Semantic dictionary mapping conceptual search queries to matching nickname IDs
const CONCEPT_SYNONYMS = {
  leader: ["reign", "titan", "chief", "prime", "kaiser", "rex", "warlord"],
  rule: ["reign", "kaiser", "rex", "zenith", "prime"],
  alone: ["rogue", "nomad", "solo", "drifter", "wolf", "exile", "stranger"],
  solo: ["solo", "nomad", "drifter", "rogue", "wolf"],
  cold: ["frost", "zero", "vanta", "glacier", "subzero", "blizzard"],
  ice: ["frost", "glacier", "subzero", "blizzard", "zero"],
  freeze: ["frost", "zero", "glacier", "subzero"],
  dark: ["shadow", "phantom", "ghost", "onyx", "void", "vanta", "cipher"],
  shadow: ["shadow", "kage", "phantom", "ghost", "specter", "onyx"],
  ghost: ["ghost", "phantom", "specter", "whisper", "shade"],
  fire: ["blaze", "inferno", "havoc", "storm", "fury"],
  burn: ["blaze", "inferno", "blizzard"],
  rebel: ["rogue", "vex", "nomad", "drifter", "outlaw", "renegade", "vandal", "riot"],
  outlaw: ["outlaw", "renegade", "rogue", "vandal"],
  silent: ["shade", "whisper", "kage", "ghost", "phantom", "specter"],
  stealth: ["ghost", "phantom", "shadow", "kage", "nomad", "whisper"],
  strong: ["titan", "colossus", "juggernaut", "ironclad", "warlord", "bane"],
  power: ["titan", "apex", "prime", "storm", "colossus", "overkill"],
  beast: ["wolf", "fenrir", "venom", "viper"],
  fast: ["viper", "apex", "blaze", "striker", "blitz"],
  king: ["rex", "reign", "kaiser", "monarch", "crown"],
  royal: ["reign", "kaiser", "rex", "zenith", "valor", "legend"],
  savage: ["venom", "viper", "reaper", "bane", "slayer", "nemesis", "warlord"],
  ruthless: ["bane", "reaper", "nemesis", "slayer", "overkill"]
};

// Curated Persona Dual Combos ("Try These Combos")
const PERSONA_COMBOS = [
  {
    id: "combo-boss-cold",
    label: "👑 Boss + 🧊 Cold",
    personas: ["boss", "cold"],
    subtitle: "Calm, calculated leadership with zero panic",
    sampleName: "Reign"
  },
  {
    id: "combo-wolf-mysterious",
    label: "🐺 Lone Wolf + 🌑 Mysterious",
    personas: ["lone-wolf", "mysterious"],
    subtitle: "Detached, enigmatic solo survivor",
    sampleName: "Nomad"
  },
  {
    id: "combo-fearless-bold",
    label: "🔥 Fearless + ⚡ Bold",
    personas: ["fearless", "bold"],
    subtitle: "Aggressive front-line energy & high swagger",
    sampleName: "Blaze"
  },
  {
    id: "combo-rebel-silent",
    label: "😈 Rebel + 🥷 Silent",
    personas: ["rebel", "silent"],
    subtitle: "Unconventional covert assassin",
    sampleName: "Rogue"
  },
  {
    id: "combo-savage-fearless",
    label: "💀 Savage + 🔥 Fearless",
    personas: ["savage", "fearless"],
    subtitle: "Brutal predator energy in squad fights",
    sampleName: "Venom"
  },
  {
    id: "combo-royal-confident",
    label: "♛ Royal + 😎 Confident",
    personas: ["royal", "confident"],
    subtitle: "High prestige with effortless mastery",
    sampleName: "Zenith"
  }
];

// Curated Collections for Attitude Explore
const CURATED_COLLECTIONS = [
  {
    id: "col-boss",
    title: "Boss Energy",
    persona: "boss",
    icon: "👑",
    badge: "Authority",
    names: ["Reign", "Titan", "Chief", "Prime", "Kaiser", "Apex"]
  },
  {
    id: "col-wolf",
    title: "Lone Wolf Syndicate",
    persona: "lone-wolf",
    icon: "🐺",
    badge: "Solo",
    names: ["Rogue", "Solo", "Nomad", "Drifter", "Wolf", "Exile"]
  },
  {
    id: "col-cold",
    title: "Cold & Calm",
    persona: "cold",
    icon: "🧊",
    badge: "Clinical",
    names: ["Frost", "Zero", "Vanta", "Glacier", "SubZero", "Blizzard"]
  },
  {
    id: "col-rebel",
    title: "Rebel Outlaws",
    persona: "rebel",
    icon: "😈",
    badge: "Defiant",
    names: ["Rogue", "Vex", "Outlaw", "Renegade", "Vandal", "Riot"]
  },
  {
    id: "col-mysterious",
    title: "Veiled Shadows",
    persona: "mysterious",
    icon: "🌑",
    badge: "Enigma",
    names: ["Phantom", "Ghost", "Shadow", "Cipher", "Onyx", "Void"]
  },
  {
    id: "col-savage",
    title: "Savage Predators",
    persona: "savage",
    icon: "💀",
    badge: "Ruthless",
    names: ["Venom", "Viper", "Reaper", "Bane", "Slayer", "Nemesis"]
  }
];
